services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sportshub
      POSTGRES_PASSWORD: sportshub
      POSTGRES_DB: sportshub
    ports:
      - "5432:5432"
    volumes:
      - sportshub_pg:/var/lib/postgresql/data

volumes:
  sportshub_pg:
